import React, { useEffect, useState } from 'react';
import { BriefcaseBusiness, CalendarDays, Mail, MapPin, Pencil, Save, ShieldCheck, UserRound } from 'lucide-react';
import { Avatar } from '../../components/ui/Avatar';
import { Button } from '../../components/ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/Card';
import { Modal } from '../../components/ui/Modal';
import { SessionUser, api } from '../../lib/api';

interface Props { user: SessionUser; token: string; onUserUpdated: (user: SessionUser) => void; }
const roleName = (role: string) => role.replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());

export function ProfileModule({ user, token, onUserUpdated }: Props) {
  const [employee, setEmployee] = useState<any | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [editing, setEditing] = useState(false); const [name, setName] = useState(user.name); const [avatarUrl, setAvatarUrl] = useState(user.avatarUrl || '');
  const [message, setMessage] = useState('');
  useEffect(() => { setName(user.name); setAvatarUrl(user.avatarUrl || ''); }, [user]);
  useEffect(() => { api.employees(token).then((result) => setEmployee(result.data.find((item: any) => String(item._id) === String(user.employee)) || null)).catch((err) => setError(err instanceof Error ? err.message : 'Unable to load employment details.')).finally(() => setLoading(false)); }, [token, user.employee]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!window.confirm('Save changes to your profile?')) return; try { const result = await api.updateProfile({ name, avatarUrl }, token); onUserUpdated(result.user); setEditing(false); setMessage('Profile updated successfully.'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update profile.'); } };
  const detail = (icon: React.ReactNode, label: string, value: string) => <div className="flex gap-3 p-3 rounded-xl bg-slate-50 border border-slate-100"><span className="mt-0.5 text-brand-600">{icon}</span><div><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-0.5 text-sm font-medium text-slate-800">{value || 'Not available'}</p></div></div>;
  return <div className="max-w-4xl mx-auto space-y-6 pb-12">
    <Card className="overflow-hidden"><div className="h-28 bg-gradient-to-r from-brand-600 to-sky-600" /><CardContent className="relative pb-7"><div className="-mt-16 flex flex-col sm:flex-row sm:items-end gap-4"><div className="rounded-full border-4 border-white bg-white shadow-md"><Avatar name={user.name} src={user.avatarUrl} size="xl" /></div><div className="flex-1"><h1 className="text-2xl font-bold text-slate-900">{user.name}</h1><p className="mt-1 text-sm text-slate-500">{employee?.title || roleName(user.role)} · {employee?.department || 'PeoplePay360 account'}</p></div><Button variant="primary" size="sm" onClick={() => setEditing(true)}><Pencil className="w-4 h-4" />Edit profile</Button></div></CardContent></Card>
    {message && <p className="rounded-lg bg-emerald-50 p-3 text-xs text-emerald-700">{message}</p>}{error && <p className="rounded-lg bg-rose-50 p-3 text-xs text-rose-700">{error}</p>}
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6"><Card><CardHeader><div className="flex gap-2 items-center"><UserRound className="w-4 h-4 text-brand-600" /><CardTitle>Personal information</CardTitle></div><CardDescription>Information associated with your account.</CardDescription></CardHeader><CardContent className="grid gap-3">{detail(<Mail className="w-4 h-4" />, 'Email', user.email)}{detail(<ShieldCheck className="w-4 h-4" />, 'Access role', roleName(user.role))}{detail(<BriefcaseBusiness className="w-4 h-4" />, 'Employee ID', employee?.employeeCode || 'Not linked')}</CardContent></Card><Card><CardHeader><div className="flex gap-2 items-center"><BriefcaseBusiness className="w-4 h-4 text-brand-600" /><CardTitle>Employment information</CardTitle></div><CardDescription>Managed by your HR team.</CardDescription></CardHeader><CardContent className="grid gap-3">{detail(<BriefcaseBusiness className="w-4 h-4" />, 'Department & title', employee ? `${employee.department} · ${employee.title}` : '')}{detail(<MapPin className="w-4 h-4" />, 'Location', employee?.location || '')}{detail(<CalendarDays className="w-4 h-4" />, 'Joined', employee?.joinDate ? new Date(employee.joinDate).toLocaleDateString() : '')}</CardContent></Card></div>
    {loading && <p className="text-xs text-slate-500">Loading profile details…</p>}
    <Modal isOpen={editing} onClose={() => setEditing(false)} title="Edit profile" description="Update the name and photo displayed in PeoplePay360."><form className="space-y-4" onSubmit={save}><div className="flex items-center gap-3"><Avatar name={name} src={avatarUrl} size="lg" /><p className="text-xs text-slate-500">Your photo will be visible across the application.</p></div><label className="block text-xs font-semibold text-slate-700">Display name<input value={name} onChange={(e) => setName(e.target.value)} required className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label><label className="block text-xs font-semibold text-slate-700">Photo URL<input type="url" value={avatarUrl} onChange={(e) => setAvatarUrl(e.target.value)} placeholder="https://example.com/photo.jpg" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" size="sm" onClick={() => setEditing(false)}>Cancel</Button><Button type="submit" variant="primary" size="sm"><Save className="w-4 h-4" />Save changes</Button></div></form></Modal>
  </div>;
}
